### ISSUE TITLE
Backup not working if PPP.py and *.m3u files in same folder

### ISSUE THREAD

**Issue by brittonbowman** [XDGFX/PPP#3]
Using a network shared folder with the same relative path (e.g. /media/MusicShare/Playlist/) for both local and plex machines.  With both the PPP.py and *.m3u files located in this same networked folder the backup will run very deep with many recursive folders of the same content and end with error 'shutil.SameFileError: '/media/MusicShare/Playlist/tmp/local/test.m3u' and 'tmp/local/test.m3u' are the same file'

Moving the PPP.py to a different folder on the same network drive (e.g. media/MusicShare/PPP/) solved the recursive backup problem.

**Comment by XDGFX** [comment]
Hmm, I can imagine running the script in the same folder as your playlists isn't ideal. I made backups include everything in your local_playlists directory including folder structure and any other files like images, smart playlists, or in this case the PPP temporary directory, which means there are duplicates.

I don't recommend keeping PPP in your local_playlists folder as you'll end up with loads of backups of the script - however I have just updated the code to use a global tmp directory (instead of PPP/tmp/) so that might have inadvertently solved this issue? If you update and try the same again please let me know if this is solved!

**Comment by brittonbowman** [comment]
The issue remains if running the ppp.py from the same dir as the playlists.

Adding a note on the installation to have in separate dir, should be fine to close the issue
